CREATE TABLE IDN_CHALLENGE_QUESTION (
    ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    QUESTION_SET_ID VARCHAR(255) NOT NULL,
    QUESTION_ID VARCHAR(255) NOT NULL,
    LOCALE VARCHAR(10) NOT NULL,
    QUESTION BLOB NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_CHALLENGE_QUESTION_CONSTRAINT UNIQUE (TENANT_ID, QUESTION_SET_ID, QUESTION_ID, LOCALE)
)
/
CREATE SEQUENCE IDN_CHALLENGE_QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE TRIGGER IDN_CHALLENGE_QUESTION_TRIG NO CASCADE
    BEFORE INSERT
    ON IDN_CHALLENGE_QUESTION
    REFERENCING NEW AS NEW
    FOR EACH ROW MODE DB2SQL
        BEGIN ATOMIC
            SET (NEW.ID) = (NEXTVAL FOR IDN_CHALLENGE_QUESTION_SEQ);
        END
/
