IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_CHALLENGE_QUESTION]') AND TYPE IN (N'U'))
CREATE TABLE IDN_CHALLENGE_QUESTION (
    ID INTEGER NOT NULL IDENTITY,
    TENANT_ID INTEGER NOT NULL,
    QUESTION_SET_ID VARCHAR(255) NOT NULL,
    QUESTION_ID VARCHAR(255) NOT NULL,
    LOCALE VARCHAR(10) NOT NULL,
    QUESTION VARBINARY(MAX) NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_CHALLENGE_QUESTION_CONSTRAINT UNIQUE (TENANT_ID, QUESTION_SET_ID, QUESTION_ID, LOCALE)
);
