DROP TABLE IF EXISTS IDN_CHALLENGE_QUESTION;
DROP SEQUENCE IF EXISTS IDN_CHALLENGE_QUESTION_SEQ;
CREATE SEQUENCE IDN_CHALLENGE_QUESTION_SEQ;
CREATE TABLE IDN_CHALLENGE_QUESTION (
    ID INTEGER DEFAULT NEXTVAL('IDN_CHALLENGE_QUESTION_SEQ'),
    TENANT_ID INTEGER NOT NULL,
    QUESTION_SET_ID VARCHAR(255) NOT NULL,
    QUESTION_ID VARCHAR(255) NOT NULL,
    LOCALE VARCHAR(10) NOT NULL,
    QUESTION BYTEA NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_CHALLENGE_QUESTION_CONSTRAINT UNIQUE (TENANT_ID, QUESTION_SET_ID, QUESTION_ID, LOCALE)
);
